#include <D3D12/D3dx12.h>
#include <combaseapi.h>
#include <cstring>
#include <d3d12.h>
#include <dxgi.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <dxgiformat.h>
#include <dxgicommon.h>
#include <handleapi.h>
#include <ratio>
#include <stdlib.h>
#include <synchapi.h>
#include <winbase.h>
#include <wrl.h>
#include <iostream>
#include <SDL3/SDL.h>
#include <windows.h>
#include <intsafe.h>
#include <wrl/client.h>
#include "D3D12/d3d12.h"
#include "D3D12/d3d12sdklayers.h"
#include "D3D12/d3dcommon.h"
#include "D3D12/dxgicommon.h"
#include "D3D12/dxgiformat.h"
#include "SDL3/SDL_events.h"
#include "SDL3/SDL_oldnames.h"
#include "SDL3/SDL_video.h"
